version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ninjas-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ninjas-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data: